config/routes.rb
Chsdesk::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :articles
  resources :tenants 
  resources :tenant_imports
    
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  root to: 'static_pages#home'

    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email
        get :invite
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end

end

app/models/user.rb
require 'aasm_roles'
class User < ActiveRecord::Base
  include AasmRoles
  rolify
  
  attr_accessible :name, :email, :password, :password_confirmation, :tenant_id, :auth_token, :state
  has_secure_password

  has_and_belongs_to_many :roles, :join_table => :users_roles
  has_many :activities

  has_many :articles, dependent: :destroy
  belongs_to :tenant

  before_save { email.downcase! }
  before_create { generate_token(:auth_token) }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates_uniqueness_of :name, scope: :tenant_id
  validates_uniqueness_of :email, scope: :tenant_id
  validates_presence_of :password, :on => :create,
                        length: { minimum: 6 }
#  validates :password_confirmation, presence: true
  default_scope { where(tenant_id: Tenant.current_id) }


  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

 #------------------------baeapp2
  def super_admin?
    has_role?(:super_admin)
  end

  def admin?
    has_role?(:admin)
  end
  
  def site_name
    self.name || self.email.split("@").first
  end

  def username
    User.name
  end
  
  def has_role?(role)
    role_symbols.include?(role.to_sym) || role_symbols.include?(:admin)
  end
  
  def has_real_role?(role)
    role_symbols.include?(role.to_sym)
  end
  
  def role_symbols
    @role_symbols ||= roles.map {|r| r.name.underscore.to_sym }
  end

#----------------------baseapp2 end-----

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction
  respond_to :html, :json
  load_and_authorize_resource 
  skip_authorize_resource :only => [:new, :create, :pending, :suspended, :active,
     :deleted, :sort_column, :sort_direction]

  def toggle_role
    @user = User.find(params[:id])
    role = Role.find_by_name(params[:role])
    if @user.roles.include?(role)
      @user.roles.delete(role)
      flash[:notice] = "Revoked #{role.name} permissions"
    else
      @user.roles << role
      @user.save
#      track_activity @user
      flash[:notice] = "Granted #{role.name} permissions"
    end
    if request.env["HTTP_REFERER"].present?
      redirect_to :back, only_path: true 
    else
      redirect_to user_path(@user), only_path: true 
    end
  end

  def pending
      @users = User.paginate :conditions => {:state => 'pending'}, :page => params[:page], :per_page => 20
    render :action => 'index'
  end

  def suspended
      @users = User.paginate :conditions => {:state => 'suspended'}, :page => params[:page], :per_page => 20
    render :action => 'index'
  end
  
  def active
      @users = User.paginate :conditions => {:state => 'active'}, :page => params[:page], :per_page => 20
    render :action => 'index'
  end
  
  def deleted
      @users = User.paginate :conditions => {:state => 'deleted'}, :page => params[:page], :per_page => 20
    render :action => 'index'
  end
  
  def activate
    @user = User.find(params[:id])
    @user.activate!
 #     track_activity @user
    redirect_to users_path, only_path: true 
  end
  
  def suspend
    @user = User.find(params[:id])
    @user.suspend! 
#      track_activity @user
    redirect_to users_path, only_path: true 
  end

  def unsuspend
    @user = User.find(params[:id])
    @user.unsuspend! 
#      track_activity @user
    redirect_to users_path, only_path: true
  end

  def purge
    @user = User.find(params[:id])
    @user.destroy
 #     track_activity @user
    redirect_to users_url, only_path: true
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, notice: "Updated profile."
    else
      render "new"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private
  
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end



end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar = 
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit  %>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
	<div class="modal-header">
	  <a class="close" data-dismiss="modal">&#215;</a>
	  <h3>Change Role</h3>
	</div>
	<div class="modal-body">
		<h4><%= t('users.options.roles') %></h4>
		<% Role.all.each do |x| -%>
			<% if x.name.underscore.to_sym == :super_admin %>
			<% else %>
				<li>
				<%= link_to (user.has_real_role?(x.name.underscore.to_sym) ? 
				t('.take', :role => x.name.humanize.gsub(/-/, ' ')) : 
				t('.grant', :role => x.name.humanize.gsub(/-/, ' '))), 
				toggle_role_user_path(user, x.name), :method => :post %>
				</li>
			<% end %>
		<% end -%>
	</div>
</div>

app/views/users/_users.html.erb
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-striped table-condensed">
	<thead>
	  <tr>
		<th>ID</th>
		<th><%= sortable "name"%></th>
		<th><%= sortable "email" %></th>
		<th><%= sortable "state",'Status' %></th>
		<th><%= sortable "role" %></th>
		<th><%= sortable "Assign role" %></th>
		<th><%= sortable "created_at",'Requested' %></th>
		<th><%= sortable "sign_in_count",'Visits' %></th>
		<th><%= sortable "last_sign_in_at",'Last' %></th>
		<th></th>
	  </tr>
	</thead>

	<tbody>
	<% for user in @users %>
	  <tr>
		<td><%= user.id %></td>
		<td><%= link_to h(user.name || user.site_name), user_url(user) %></td>
		<td><%= user.email %></td>
		<td><% if user.active? %>
			<span class="label label-success"><%= user.state  %></span>
			<% elsif user.passive? %>
			<span class="label label-Warning"><%= user.state  %></span>
			<% elsif user.suspended? %>
			<span class="label label-important"><%= user.state  %></span>
			<% elsif user.pending? %>
			<span class="label label-inverse"><%= user.state  %></span>
			<% end %></td>
		<td><%= user.roles.map{|x| x.name.humanize }.join(", ") %></td>
		<td><a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a></td>
		<%= render user %>
		<td><%= l(user.created_at.to_date, :format => :long) %></td>
		<td><%= user.sign_in_count if user.sign_in_count %></td>
		<td><%= l(user.last_sign_in_at.to_date, :format => :long) if user.last_sign_in_at %></td>
		<td>
			<% if user.pending? %>
				<%= link_to 'Activate', activate_user_url(user), :method => :put %>
				<%= link_to 'Suspend', suspend_user_url(user), :method => :put %>
				<%= link_to ( image_tag("/assets/Overlay-cancel.png")), user_url(user), :method => :delete, :confirm => "Are you sure?" %>
			<% elsif user.passive? %>
				<%= link_to ( image_tag("/assets/Key1.png")), activate_user_url(user), :method => :put %>
				<%= link_to ( image_tag("/assets/Overlay-lock.png")), suspend_user_path(user), :method => :put %>
				<%= link_to ( image_tag("/assets/Overlay-cancel.png")), user_url(user), :method => :delete, :confirm => "Are you sure?" %>
			<% elsif user.active? %>
				<%= link_to ( image_tag("/assets/Overlay-lock.png")), suspend_user_path(user), :method => :put %>
				<%= link_to ( image_tag("/assets/Overlay-cancel.png")), user_url(user), :method => :delete, :confirm => "Are you sure?" %>
			<% elsif user.suspended? %>
				<%= link_to ( image_tag("/assets/Lock-Unlock-icon.png")), unsuspend_user_url(user), :method => :put %>
				<%= link_to ( image_tag("/assets/Overlay-cancel.png")), user_url(user), :method => :delete, :confirm => "Are you sure?" %>
			<% elsif user.deleted? %>
				<%= link_to ( image_tag("/assets/Lock-Unlock-icon.png")), unsuspend_user_url(user), :method => :put %>
				<%= link_to "Purge", purge_user_url(user), :method => :delete, :confirm => "Are you sure you want to remove this account, and all data associated with it?" %>
			<% end %>
		</td>
	  </tr>
	<% end %>
	</tbody>
</table>

<%= will_paginate @users %>

<div class="form-actions">
	<%= link_to 'Add New User', new_user_path, :class => 'btn' %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 

<div class="content-header">
	<ul class="content-header-action pull-right">
<!-- content-header -->
	<%= render 'layouts/content/header' %>
	</ul>
	<h2><i class="icofont-home"></i>Edit Profile of <%= current_user.name.to_s.humanize %>)</h2>
</div><!-- /content -header-->
	<!-- content-breadcrumb -->
<div class="content-breadcrumb">
	<ul class="breadcrumb">
		<li><a href="/"><i class="icofont-home"></i> Dashboard</a> <span class="divider">&rsaquo;</span></li>
		<li class="active">Users</li>
	</ul><!--/breadcrumb-->
</div><!-- /content-breadcrumb -->
<div class="content-body">
	<!-- form -->
	<div class="row-fluid">
		<div class="span12">
			<div class="box corner-all">
				<!--box header-->
				<div class="box-header grd-white color-silver-dark corner-top">
					<span>Profile of <%=  current_user.name %> 
					</span>
				</div><!--/box header-->

<%= render "form" %>
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>

			</div><!--/box-->
		</div><!-- span11 -->
	</div><!--/row-fluid--><!--/form-->
</div><!-- /content body-->

app/views/users/index.html.erb
<div class="content-header">
	<ul class="content-header-action pull-right">
<!-- content-header -->
	<%= render 'layouts/content/header' %>
	</ul>
	<h2><i class="icofont-home"></i> LISTING USERS (I am <%= current_user.name.to_s.humanize %>)</h2>
</div><!-- /content -header-->
	<!-- content-breadcrumb -->
<div class="content-breadcrumb">
	<ul class="breadcrumb">
		<li><a href="/"><i class="icofont-home"></i> Dashboard</a> <span class="divider">&rsaquo;</span></li>
		<li class="active">Users</li>
	</ul><!--/breadcrumb-->
</div><!-- /content-breadcrumb -->

<!--box-->
<div class="content-body">
	<!-- form -->
	<div class="row-fluid">
		<div class="span12">
			<div class="box corner-all">
				<!--box header-->
				<div class="box-header grd-white color-silver-dark corner-top">
					<span>Total <%=  @users.count %> Users
					</span>
				</div><!--/box header-->
				<!--box body-->
					<div class="controls">
						<h4>Filter Users:&nbsp;&nbsp;<%= link_to t('.options.all'), users_url %> 
						&#183;&nbsp;<%= link_to t('.options.active'), active_users_url %>
						&#183;&nbsp;<%= link_to t('.options.suspended'), suspended_users_url %>
						&#183;&nbsp;<%= link_to t('.options.pending'), pending_users_url %>
						&#183;&nbsp;<%= link_to t('.options.deleted'), deleted_users_url %>
						<span class="pull-right" ><%= form_tag users_path, :method => 'get', :id => "users_search" do %>
						<%= text_field_tag :search, params[:search], :placeholder => 'Search by Name' %>
						<% end %></span></h4>
						<div id="users"><%= render 'users' %></div>
					</div>
			</div><!--/box-->
		</div><!-- span11 -->
	</div><!--/row-fluid--><!--/form-->
</div><!-- /content body-->

app/views/users/index.js.erb
$("#users").html("<%= escape_javascript(render("users")) %>");

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="container">
	<div class="signin-form row-fluid">
		<!--Sign Up-->
		<div class="span6">
			<div class="box corner-all">
				<div class="box-header grd-green color-white corner-top">
					<span>Create an account!</span>
				</div>
				<div class="box-body bg-white">
				<%= simple_form_for( @user, :html => {:class => 'form-vertical' }) do |f| %>
					<form id="sign-up" method="post">
						<div class="control-group">
							<label class="control-label">Username</label>
							<div class="controls">
								<input type="text" class="input-block-level" data-validate="{required: true, messages:{required:'Please enter field username'}}" name="user[name]" id="user_name" autocomplete="off" />
								<p class="help-block muted helper-font-small">May contain letters, digits, dashes and underscores, and should be between 2 and 20 characters long.</p>
							</div>
						</div>
						<div class="control-group">
						<label class="control-label">Email</label>
						<div class="controls">
							<input type="text" class="input-block-level" data-validate="{required: true, email:true, messages:{required:'Please enter field email', email:'Please enter a valid email address'}}" name="user[email]" id="user_email" autocomplete="off" />
							<p class="help-block muted helper-font-small"><strong>Type carefully.</strong> You will be sent a confirmation email.</p>
						</div>
						</div>
						<div class="control-group">
							<label class="control-label">Password</label>
							<div class="controls">
								<input type="password" class="input-block-level" data-validate="{required: true, minlength: 6, messages:{required:'Please enter field password', minlength:'Please enter at least 6 characters.'}}" name="user[password]" id="user_password" autocomplete="off" />
								<p class="help-block muted helper-font-small">The longer the better. Include numbers for protein.</p>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Password Again</label>
							<div class="controls">
								<input type="password" class="input-block-level" data-validate="{required: true, equalTo: '#password', messages:{required:'Please enter field confirm password', equalTo: 'confirmation password does not match the password'}}" name="user[password_confirmation]" id="user_password_confirmation" autocomplete="off" />
								<p class="help-block muted helper-font-small">Enter your password again.</p>
							</div>
						</div>
						<div class="control-group">
							<p class="term-of-use">Lorem ipsum dolor sit amet, natoque per at morbi at vestibulum leo, velit non, curabitur ac est. <a href="#">terms of use</a> and <a href="#">privacy policy</a>.</p>
						</div>
						<div class="control-group">
							<label class="checkbox">
								<input type="checkbox" data-form="uniform" name="subscribe" id="subscribe_yes" value="yes" checked> Sign me up for the newsletter
							</label>
						</div>
						<div class="form-actions">
							<input type="submit" class="btn btn-block btn-large btn-success" value="Create account" />
						</div>
						<% end %>
					</form>
				</div>
			</div>
		</div><!--/Sign Up-->
	</div><!-- /row -->
</div><!-- /container -->

<!-- javascript
================================================== -->

<script type="text/javascript">
$(document).ready(function() {
	// uniform
	$('[data-form=uniform]').uniform();
	// validate
	$('#sign-up').validate();
})
</script>