config/routes.rb
Chsdesk::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :articles
  resources :tenants 
  resources :tenant_imports
    
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  root to: 'static_pages#home'

    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email
        get :invite
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end

end

app/views/layouts/header/_button.html.erb
<div class="btn-group">
    <!--notification-->
    <a class="btn btn-danger btn-small" data-toggle="dropdown" href="#" title="3 notification">3</a>
    <ul class="dropdown-menu dropdown-notification">
        <li class="dropdown-header grd-white"><a href="#">View All Notifications</a></li>
        <li class="new">
            <a href="#">
                <div class="notification">Request new order</div>
                <div class="media">
                    <img class="media-object pull-left" data-src="js/holder.js/64x64" />
                    <div class="media-body">
                        <h4 class="media-heading">Lacinia non</h4>
                        <p>Messenger bag gentrify pitchfork tattooed craft beer.</p>
                    </div>
                </div>
            </a>
        </li>
        <!-- <li class="dropdown-footer"><a href=""></a></li> -->
    </ul><!--notification-->
</div>
<div class="btn-group">
    <a class="btn btn-inverse btn-small dropdown-toggle" data-toggle="dropdown" href="#">
        Shortcut
    </a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><a tabindex="-1" href="calendar.html">Calendar</a></li>
        <li><a tabindex="-1" href="invoice.html">Invoice</a></li>
        <li><a tabindex="-1" href="message.html">Message</a></li>
        <li class="divider"></li>
        <li class="dropdown-submenu">
            <a tabindex="-1" href="#">Sample Page</a>
            <ul class="dropdown-menu">
                <li><a tabindex="-1" href="pricing.html">Pricing</a></li>
                <li><a tabindex="-1" href="bonus-page/resume/index.html">Resume</a></li>
            </ul>
        </li>
        <li class="dropdown-submenu">
            <a tabindex="-1" href="#">Error Page</a>
            <ul class="dropdown-menu">
                <li><a tabindex="-1" href="403.html">Error 403</a></li>
                <li><a tabindex="-1" href="404.html">Error 404</a></li>
                <li><a tabindex="-1" href="405.html">Error 405</a></li>
                <li><a tabindex="-1" href="500.html">Error 500</a></li>
                <li><a tabindex="-1" href="503.html">Error 503</a></li>
                <li><a tabindex="-1" href="under-construction.html">Under Construction</a></li>
                <li><a tabindex="-1" href="coming-son.html">Coming Son</a></li>
            </ul>
        </li>
        <li class="divider"></li>
        <li><a tabindex="-1" href="#">Something else here</a></li>
    </ul>
</div>
<div class="btn-group ">
    <a class="btn btn-inverse btn-small dropdown-toggle" data-toggle="dropdown" href="#">
        Menu
    </a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><a tabindex="-1" href="/">Home</a></li>
        <li><a tabindex="-1" href="/help">Help</a></li>
        <li class="divider"></li>
		<% if current_user %>
        <li><a tabindex="-1" href=""><%= link_to ('Logout'), logout_path %></a></li>
        <li><a tabindex="-2" href=""><%= link_to 'Edit account', edit_user_path(current_user) %></a></li>
			<% if current_user.has_role? :admin %>
        <li><a tabindex="-3" href=""> <%= link_to 'Admin', users_path %></a></li>
			<% end %>
		<% else %>
        <li><a tabindex="-1" href=""><%= link_to('Login', login_path) %></a></li>
        <li><a tabindex="-2" href=""><%= link_to('Sign up', signup_path) %></a></li>
		<% end %>

        <li class="active"><a tabindex="-1" href="layout_toggleright2.html">Toggle Right Alt</a></li>
    </ul>
</div>

app/views/layouts/header/_search.html.erb
<div class="panel-search">
    <form class="form-search">
        <div class="input-icon-append">
            <button type="submit" rel="tooltip-bottom" title="search" class="icon"><i class="icofont-search"></i></button>
            <input class="input-large search-query grd-white" maxlength="23" placeholder="Search here..." type="text">
        </div>
    </form>
</div><!--/panel search-->

app/views/layouts/header/_sitelogo.html.erb
<% if current_user %>
	<div class="panel-sitename">
		<h3><a href="/"><span class="color-teal"><%= current_user.tenant.name.to_s.humanize %></span></a></h3>
	</div>
<% else %>
	<div class="panel-sitename">
		<h2><a href="index.html"><span class="color-teal">CHS</span>Desk</a></h2>
	</div>
<% end %>