config/routes.rb
Chsdesk::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :articles
  resources :tenants 
  resources :tenant_imports
    
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  root to: 'static_pages#home'

    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email
        get :invite
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end

end

app/views/layouts/_content.html.erb
<%= render 'layouts/content/span6' %>
<%= render 'layouts/content/tab' %>
<!--schedule-->
<div class="divider-content"><span></span></div>
<%= render 'layouts/content/schedule' %>
<!--schedule-->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
	<%= render 'layouts/stylesheets' %>

<div class="navbar-helper">
	<div class="row-fluid">
		<!--panel site-name-->
		<div class="span6">
			<%= render 'layouts/header/sitelogo' %>
		<!--/panel name-->
		</div>
		<div class="span3">
			<!--panel search-->
			<%= render 'layouts/header/search' %>
		</div>
		<div class="span3">
			<!--panel button ext-->
			<div class="panel-ext">
				<%= render 'layouts/header/button' %>
				<div class="btn-group user-group">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
								<% if current_user %>
						<img class="corner-all" align="middle" src="../img/guest.png" title=<%= current_user.name.to_s.humanize %> alt=<%= current_user.name.to_s.humanize %> /> <!--this for display on PC device-->
						<button class="btn btn-small btn-inverse"><%= current_user.name.to_s.humanize %></button> <!--this for display on tablet and phone device-->
								<% else %>
						<img class="corner-all" align="middle" src= "../img/user-thumb.jpg" title= "" alt= "" /> <!--this for display on PC device-->
						<button class="btn btn-small btn-inverse"></button> <!--this for display on tablet and phone device-->
								<% end %>
					</a>
					<ul class="dropdown-menu dropdown-user" role="menu" aria-labelledby="dLabel">
						<li>
							<div class="media">
								<a class="pull-left" href="#">
									<img class="img-circle" src="../img/user.jpg" title="profile" alt="profile" />
								</a>
								<div class="media-body description">
								<% if current_user %>
									<p><strong><%= link_to (current_user.name), users_path, :placeholder => 'Site controllar' %></strong></p>
									<p class="muted"><%= link_to (current_user.email), users_path %></p>
									<p class="action"><a class="link" href="#">Activity</a> - <a class="link" href="#">Setting</a></p>
									<a class="btn btn-primary btn-small btn-block" <%= link_to 'View Profile', current_user  %> </a>
								<% end %>
								</div>
							</div>
						</li>
						<li class="dropdown-footer">
							<div>
							</div>
						</li>
					</ul>
				</div>
			</div><!--panel button ext-->
		</div>
	</div><!--/row-fluid-->
</div><!--/nav bar helper-->

app/views/layouts/_javascript.html.erb
<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.1.1.js"></script>
<script src="/js/jquery-ui.min.js"></script>
<script src="/js/uniform/jquery.uniform.js"></script>
<script src="/js/peity/jquery.peity.js"></script>

<script src="/js/select2/select2.js"></script>
<script src="/js/knob/jquery.knob.js"></script>
<script src="/js/flot/jquery.flot.js"></script>
<script src="/js/flot/jquery.flot.resize.js"></script>
<script src="/js/flot/jquery.flot.categories.js"></script>
<script src="/js/wysihtml5/wysihtml5-0.3.0.js"></script>
<script src="/js/wysihtml5/bootstrap-wysihtml5.js"></script>
<script src="/js/calendar/fullcalendar.js"></script> <!-- this plugin required jquery ui-->

<script src="/js/validate/jquery.metadata.js"></script>
<script src="/js/validate/jquery.validate.js"></script>
<script src="/js/wizard/jquery.ui.widget.js"></script> <!-- this required for jquery.wizard-->
<script src="/js/wizard/jquery.wizard.js"></script>

<!-- required stilearn template js, for full feature-->
<script src="/js/holder.js"></script>
<script src="/js/stilearn-base.js"></script>
<[if lt IE 9]>
  <script src="/js/html5shiv.js"></script>
<[endif]>
<script type="text/javascript">
    $(document).ready(function() {
        // try your js
        
        // normalize event tab-stat, we hack something here couse the flot re-draw event is any some bugs for this case
        $('#tab-stat > a[data-toggle="tab"]').on('shown', function(){
            if(sessionStorage.mode == 4){ // this hack only for mode side-only
                $('body,html').animate({
                    scrollTop: 0
                }, 'slow');
            }
        });
        
        // peity chart
        $("span[data-chart=peity-bar]").peity("bar");
        
        // Input tags with select2
        $('input[name=reseiver]').select2({
            tags:[]
        });
        
        // uniform
        $('[data-form=uniform]').uniform();
        
        // wysihtml5
        $('[data-form=wysihtml5]').wysihtml5()
        toolbar = $('[data-form=wysihtml5]').prev();
        btn = toolbar.find('.btn');
        
        $.each(btn, function(k, v){
            $(v).addClass('btn-mini')
        });
        
        // Server stat circular by knob
        $("input[data-chart=knob]").knob();
        
        // system stat flot
        d1 = [ ['jan', 231], ['feb', 243], ['mar', 323], ['apr', 352], ['maj', 354], ['jun', 467], ['jul', 429] ];
        d2 = [ ['jan', 87], ['feb', 67], ['mar', 96], ['apr', 105], ['maj', 98], ['jun', 53], ['jul', 87] ];
        d3 = [ ['jan', 34], ['feb', 27], ['mar', 46], ['apr', 65], ['maj', 47], ['jun', 79], ['jul', 95] ];
        
        var visitor = $("#visitor-stat"),
        order = $("#order-stat"),
        user = $("#user-stat"),
        
        data_visitor = [{
                data: d1,
                color: '#00A600'
            }],
        data_order = [{
                data: d2,
                color: '#2E8DEF'
            }],
        data_user = [{
                data: d3,
                color: '#DC572E'
            }],
         
        
        options_lines = {
            series: {
                lines: {
                    show: true,
                    fill: true
                },
                points: {
                    show: true
                },
                hoverable: true
            },
            grid: {
                backgroundColor: '#FFFFFF',
                borderWidth: 1,
                borderColor: '#CDCDCD',
                hoverable: true
            },
            legend: {
                show: false
            },
            xaxis: {
                mode: "categories",
                tickLength: 0
            },
            yaxis: {
                autoscaleMargin: 2
            }

        };
        
        // render stat flot
        $.plot(visitor, data_visitor, options_lines);
        $.plot(order, data_order, options_lines);
        $.plot(user, data_user, options_lines);
        
        // tootips chart
        function showTooltip(x, y, contents) {
            $('<div id="tooltip" class="bg-black corner-all color-white">' + contents + '</div>').css( {
                position: 'absolute',
                display: 'none',
                top: y + 5,
                left: x + 5,
                border: '0px',
                padding: '2px 10px 2px 10px',
                opacity: 0.9,
                'font-size' : '11px'
            }).appendTo("body").fadeIn(200);
        }

        var previousPoint = null;
        $('#visitor-stat, #order-stat, #user-stat').bind("plothover", function (event, pos, item) {
            
            if (item) {
                if (previousPoint != item.dataIndex) {
                    previousPoint = item.dataIndex;

                    $("#tooltip").remove();
                    var x = item.datapoint[0].toFixed(2),
                    y = item.datapoint[1].toFixed(2);
                    label = item.series.xaxis.ticks[item.datapoint[0]].label;
                    
                    showTooltip(item.pageX, item.pageY,
                    label + " = " + y);
                }
            }
            else {
                $("#tooltip").remove();
                previousPoint = null;            
            }
            
        });
        // end tootips chart
        
        
        // Schedule Calendar
        var date = new Date();
var d = date.getDate();
var m = date.getMonth();
var y = date.getFullYear();

        var calendar = $('#schedule').fullCalendar({
            header: {
                left: 'title',
                center: '',
                right: 'prev,next today,month,basicWeek,basicDay'
            },
            events: [
                {
                    title: 'Start a project',
                    start: new Date(y, m, 1)
                },
                {
                    title: 'interview and data collection',
                    start: new Date(y, m, 3),
                    end: new Date(y, m, 7)
                },
                {
                    title: 'Creating design interface',
                    start: new Date(y, m, 9),
                    end: new Date(y, m, 12)
                },
                {
                    title: 'Meeting',
                    start: new Date(y, m, 19, 10, 30),
                    allDay: false
                },
                {
                    title: 'Meeting',
                    start: new Date(y, m, 28, 10, 30),
                    allDay: false
                },
                {
                    title: 'Date',
                    start: new Date(y, m, d, 12, 0),
                    end: new Date(y, m, d, 14, 0),
                    allDay: false
                },
                {
                    title: 'Birthday Party',
                    start: new Date(y, m, d+1, 19, 0),
                    end: new Date(y, m, d+1, 22, 30),
                    allDay: false
                }
            ]
        });
        // end Schedule Calendar
        // validate form
        $('#form-validate').validate();
        
        // wizard
        $('#form-wizard').wizard({
            stepsWrapper: "#wrapped",
            submit: ".submit",
            beforeSelect: function( event, state ) {
                var inputs = $(this).wizard('state').step.find(':input');
                return !inputs.length || !!inputs.valid();
            }
        }).submit(function( event ) {
            event.preventDefault();
            alert('Form submitted!');
        }).wizard('form').validate({
            errorPlacement: function(error, element) { 
                if ( element.is(':radio') || element.is(':checkbox') ) {
                        $('#error-gender').html(error);
                    } else { 
                            error.insertAfter( element );
                    }
                }
            });
        });
  
</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sideleft.html.erb
<aside class="side-left">
    <ul class="sidebar">
        <li class="active first"> <!--always define class .first for first-child of li element sidebar left-->
            <a href="/" title="dashboard">
                <div class="helper-font-24">
                    <i class="icofont-dashboard"></i>
                </div>
                <span class="sidebar-text">Dashboard</span>
            </a>
        </li>
        <% if current_user %>
		<li >
            <a href="/users" title="Users">
                <div class="helper-font-24">
                    <i class="icofont-magnet"></i>
                </div>
                <span class="sidebar-text">Users</span>
            </a>
        </li>
		<% end %>
	    <li>
            <a href="#" title="form">
                <div class="badge badge-important">3</div>
                <div class="helper-font-24">
                    <i class="icofont-edit"></i>
                </div>
                <span class="sidebar-text">Form</span>
            </a>
            <ul class="sub-sidebar-form corner-top shadow-white">
                <li class="title muted">Quick Upload</li>
                <li>
                    <input type="file" data-form="uniform" onchange="alert('your progres uploading file...')" />
                </li>
                <li class="divider"></li>
                <li>
                    <a href="form.html" title="form element" class="corner-all">
                        <i class="icofont-file"></i>
                        <span class="sidebar-text">Form Element</span>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="code_editor.html" title="code editor" class="corner-all">
                        <i class="icofont-book"></i>
                        <span class="sidebar-text">Code Editor</span>
                    </a>
                </li>
                <li>
                    <a href="gallery.html" title="gallery" class="corner-all">
                        <i class="icofont-picture"></i>
                        <span class="sidebar-text">Gallery</span>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#" title="charts">
                <div class="helper-font-24">
                    <i class="icofont-bar-chart"></i>
                </div>
                <span class="sidebar-text">charts</span>
            </a>
        </li>
        <li>
            <a href="#" title="table">
                <div class="helper-font-24">
                    <i class="icofont-table"></i>
                </div>
                <span class="sidebar-text">Tables</span>
            </a>
        </li>
        <li>
            <a href="#" title="grids">
                <div class="helper-font-24">
                    <i class="icofont-columns"></i>
                </div>
                <span class="sidebar-text">Grids</span>
            </a>
        </li>
        <li>
            <a href="#" title="icons">
                <div class="helper-font-24">
                    <i class="icofont-star"></i>
                </div>
                <span class="sidebar-text">Icons</span>
            </a>
        </li>
        <li>
            <a href="/activities" title="widgets">
                <div class="helper-font-24">
                    <i class="icofont-reorder"></i>
                </div>
                <span class="sidebar-text">Activity Log</span>
            </a>
        </li>
        <li>
            <a href="#" title="more">
                <div class="badge badge-important">5</div>
                <div class="helper-font-24">
                    <i class="icofont-th-large"></i>
                </div>
                <span class="sidebar-text">More</span>
            </a>
            <ul class="sub-sidebar corner-top shadow-silver-dark">
                <li>
                    <a href="404.html" title="not found">
                        <div class="helper-font-24">
                            <i class="icofont-warning-sign"></i>
                        </div>
                        <span class="sidebar-text">404</span>
                    </a>
                </li>
                <li>
                    <a href="#" title="login">
                        <div class="helper-font-24">
                            <i class="icofont-lock"></i>
                        </div>
                        <span class="sidebar-text">Login</span>
                    </a>
                </li>
                <li>
                    <a href="#" title="invoice">
                        <div class="helper-font-24">
                            <i class="icofont-barcode"></i>
                        </div>
                        <span class="sidebar-text">Invoice</span>
                    </a>
                </li>
                <li>
                    <a href="#" title="pricing table">
                        <div class="helper-font-24">
                            <i class="icofont-briefcase"></i>
                        </div>
                        <span class="sidebar-text">Pricing</span>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="bonus-page/resume/index.html" title="resume">
                        <div class="helper-font-24">
                            <i class="icofont-user"></i>
                        </div>
                        <span class="sidebar-text">Resume</span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</aside><!--/side bar -->

app/views/layouts/_sideright.html.erb
<!-- side-right -->
<a class="sideright-toggle-nav" href="#"><i class="icofont-arrow-left"></i></a>
<aside class="side-right side-right-large" data-toggle="on">
    <!-- sidebar-right -->
    <div class="sidebar-right">
        <!--sidebar-right-header-->
        <div class="sidebar-right-header">
            <div class="sr-header-right">
                <h2><span class="label label-info">$26,875</span></h2>
            </div>
            <div class="sr-header-left">
                <p class="bold">Balance</p>
                <small class="muted">Dec 30 2012</small>
            </div>
        </div><!--/sidebar-right-header-->
        <!--sidebar-right-control-->
        <div class="sidebar-right-control">
            <ul class="sr-control-item">
                <li class="active"><a href="#contact" data-toggle="tab" title="contacts"><i class="icofont-group"></i></a></li>
                <li><a href="#alt1" data-toggle="tab" title="alternative 1"><i class="icofont-flag"></i></a></li>
                <li rel="tooltip-bottom" title="view site"><a href="index.html" target="_BLANK"><i class="icofont-external-link"></i></a></li>
            </ul>
        </div><!-- /sidebar-right-control-->
        <!-- sidebar-right-content -->
        <div class="sidebar-right-content">
            <div class="tab-content">
                
                <!--chat-->
                <div class="tab-pane fade" id="chat">
                    <div class="side-chat">
                        <!--header part-->
                        <div class="chat-header">
                            <div class="chat-action">
                                <div class="btn-group pull-right">
                                    <!--we use data toggle tab for navigate this action-->
                                    <a class="bg-transparent no-border" href="#contact" data-toggle="tab" title="minimize"><i class="icofont-minus"></i></a>
                                    <a class="bg-transparent no-border" title="pop out"><i class="icofont-resize-full"></i></a>
                                    <a class="bg-transparent no-border" href="#contact" data-toggle="tab" title="close"><i class="icofont-remove-sign"></i></a>
                                </div>
                            </div>
                            <h5><i class="icofont-certificate color-green"></i> Jane smith</h5>
                        </div>
                        <!--content part-->
                        <div class="chat-content">
                            <div class="chat-in">
                                <span class="chat-time">10:45am</span>
                                <strong class="chat-user">Jane smith: </strong>
                                <div class="chat-text">Lorem ipsum dolor</div>
                            </div>
                            <div class="chat-out">
                                <span class="chat-time">10:47am</span>
                                <strong class="chat-user">me: </strong>
                                <div class="chat-text">Erat duis lectus vel wisi, quibusdam aliquam vehicula eleifend ut</div>
                            </div>
                            <div class="chat-in">
                                <span class="chat-time">10:50am</span>
                                <strong class="chat-user">Jane smith: </strong>
                                <div class="chat-text">Et sagittis ut vel dolor nullam proin</div>
                            </div>
                            <div class="chat-out">
                                <span class="chat-time">10:52am</span>
                                <strong class="chat-user">me: </strong>
                                <div class="chat-text">massa massa quisque sodales id dictumst.</div>
                            </div>
                        </div>
                        <!--status typed part-->
                        <div class="chat-typed"><i class="typicn-chat"></i> Jane smith is typing...</div>
                        <!--input part-->
                        <div class="chat-input">
                            <div class="chat-desc muted">Lorem ipsum dolor sit amet.</div>
                            <textarea class="input-block-level" placeholder="chat here..."></textarea>
                        </div>
                    </div>
                    <div class="divider-content"><span></span></div>
                </div><!--chat-->
                
                <!--contact-->
                <div class="tab-pane fade active in" id="contact">
                    <div class="side-contact">
                        <!--contact-control-->
                        <!--contact-search-->
                        <!--contact-list, we set this max-height:380px, you can set this if you want-->
                        <ul class="contact-list">
                        </ul><!--/contact-list-->
                    </div>
                </div><!--/contact-->
                
                <!--alternative 1-->
                <div class="tab-pane fade" id="alt1">
                    
                </div><!--/alternative 1-->
                
            </div>
        </div><!-- /sidebar-right-content -->
    </div><!-- /sidebar-right -->
</aside><!-- /side-right -->

app/views/layouts/_stylesheets.html.erb
		<!-- styles -->
		<!-- default theme -->
		<link id="style-base" href="/css/stilearn.css" rel="stylesheet">
		<link id="style-responsive" href="/css/stilearn-responsive.css" rel="stylesheet">
		<link id="style-helper" href="/css/stilearn-helper.css" rel="stylesheet">
		<!-- usage -->
		<link href="/css/stilearn-icon.css" rel="stylesheet">
		<link href="/css/font-awesome.css" rel="stylesheet">
		<link href="/css/animate.css" rel="stylesheet">
		<link href="/css/uniform.default.css" rel="stylesheet">
		<!-- other -->
		<link href="/css/select2.css" rel="stylesheet">
		<link href="/css/fullcalendar.css" rel="stylesheet">
		<link href="/css/bootstrap-wysihtml5.css" rel="stylesheet">

		<link href="/css/resume.css" rel="stylesheet">
		<link href="/css/resume-control.css" rel="stylesheet">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta name="author" content="chsdesk">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= content_for?(:title) ? yield(:title) : "Chsdesk Saas" %></title>
	<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chsdesk Saas" %>">
	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= render 'layouts/stylesheets' %>
	<!-- google font -->
	<link href="http://fonts.googleapis.com/css?family=Aclonica:regular" rel="stylesheet" type="text/css" />
		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
          <script src="js/html5shiv.js"></script>
        <![endif]-->
	<%= csrf_meta_tags %>
		
  </head>

  <body>
	<!-- section header -->
	<header class="header">
		<!--nav bar helper-->
		<%= render 'layouts/header' %>
	</header>

	<!-- section content -->
	<section class="section">
		<div class="row-fluid">
			<!-- span side-left -->
			<div class="span1">
				<!--side bar-->
				<%= render 'layouts/sideleft' %>
			</div><!-- span side-left -->
			<!-- span content -->
			<div class="span11">
			<!-- content -->
				<div class="content content-large">
					<!-- content-header -->
					<%= render 'layouts/messages' %>
					<%= yield %>
				</div><!-- /content content-large-->
			</div><!-- /span 11 --><!-- span content -->
			<div class="span5">
				<%= render 'layouts/sideright' %>
			<!-- span side-right -->
			</div><!-- /span side-right -->
		</div><!-- /row -->
	</section><!-- /section content -->
	<!-- section footer -->
	<footer>
		<a rel="to-top" href="#top"><i class="icofont-circle-arrow-up"></i></a>
	</footer>
		<!-- javascript
        ================================================== -->
		<%= javascript_include_tag "application" %>
				<%= render 'layouts/javascript' %>
    </body>
</html>